-- =============================================
-- Script de configuración de base de datos para XA57_Proyecto
-- Este script crea la base de datos completa con todas las tablas y datos iniciales
-- Compatible con PostgreSQL
-- =============================================

-- Este script debe ejecutarse en dos pasos:
-- Paso 1: Crear la base de datos (sin conectar)
-- Paso 2: Ejecutar este script nuevamente ya conectado a xa57_db

-- Verificar que estamos conectados a xa57_db
DO $$
BEGIN
    IF current_database() <> 'xa57_db' THEN
        RAISE NOTICE 'Por favor conéctese a la base de datos xa57_db antes de ejecutar este script.';
        RAISE NOTICE ' use: \c xa57_db';
    ELSE
        RAISE NOTICE 'Conectado a xa57_db, creando tablas...';
    END IF;
END $$;

-- =============================================
-- Tablas de Identity de ASP.NET Core
-- =============================================

CREATE TABLE IF NOT EXISTS "AspNetUsers" (
    "Id" TEXT NOT NULL PRIMARY KEY,
    "AccessFailedCount" INTEGER NOT NULL,
    "Apellido" CHARACTER VARYING(100) NOT NULL,
    "ConcurrencyStamp" TEXT,
    "Email" CHARACTER VARYING(256),
    "EmailConfirmed" BOOLEAN NOT NULL,
    "LockoutEnabled" BOOLEAN NOT NULL,
    "LockoutEnd" TIMESTAMP WITH TIME ZONE,
    "Nombre" CHARACTER VARYING(100) NOT NULL,
    "NormalizedEmail" CHARACTER VARYING(256),
    "NormalizedUserName" CHARACTER VARYING(256),
    "PasswordHash" TEXT,
    "PhoneNumber" TEXT,
    "PhoneNumberConfirmed" BOOLEAN NOT NULL,
    "SecurityStamp" TEXT,
    "TwoFactorEnabled" BOOLEAN NOT NULL,
    "UserName" CHARACTER VARYING(256)
);

CREATE UNIQUE INDEX IF NOT EXISTS "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
CREATE INDEX IF NOT EXISTS "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE TABLE IF NOT EXISTS "AspNetRoles" (
    "Id" TEXT NOT NULL PRIMARY KEY,
    "ConcurrencyStamp" TEXT,
    "Name" CHARACTER VARYING(256),
    "NormalizedName" CHARACTER VARYING(256)
);

CREATE UNIQUE INDEX IF NOT EXISTS "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE TABLE IF NOT EXISTS "AspNetRoleClaims" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ClaimType" TEXT,
    "ClaimValue" TEXT,
    "RoleId" TEXT NOT NULL,
    FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE TABLE IF NOT EXISTS "AspNetUserClaims" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ClaimType" TEXT,
    "ClaimValue" TEXT,
    "UserId" TEXT NOT NULL,
    FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE TABLE IF NOT EXISTS "AspNetUserLogins" (
    "LoginProvider" CHARACTER VARYING(128) NOT NULL,
    "ProviderKey" CHARACTER VARYING(128) NOT NULL,
    "ProviderDisplayName" TEXT,
    "UserId" TEXT NOT NULL,
    PRIMARY KEY ("LoginProvider", "ProviderKey"),
    FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE TABLE IF NOT EXISTS "AspNetUserRoles" (
    "UserId" TEXT NOT NULL,
    "RoleId" TEXT NOT NULL,
    PRIMARY KEY ("UserId", "RoleId"),
    FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE TABLE IF NOT EXISTS "AspNetUserTokens" (
    "UserId" TEXT NOT NULL,
    "LoginProvider" CHARACTER VARYING(128) NOT NULL,
    "Name" CHARACTER VARYING(128) NOT NULL,
    "Value" TEXT,
    PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

-- =============================================
-- Tablas de la aplicación
-- =============================================

CREATE TABLE IF NOT EXISTS "tipos_producto" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "max_caracteres" INTEGER NOT NULL,
    "nombre" TEXT NOT NULL,
    "permite_nombre" BOOLEAN NOT NULL,
    "permite_numero_economico" BOOLEAN NOT NULL,
    "permite_ruta" BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS "productos" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "activo" BOOLEAN NOT NULL,
    "descripcion" TEXT NOT NULL,
    "imagen_url" TEXT NOT NULL,
    "nombre" TEXT NOT NULL,
    "precio" NUMERIC NOT NULL,
    "tipo_producto_id" INTEGER,
    FOREIGN KEY ("tipo_producto_id") REFERENCES "tipos_producto" ("id")
);

CREATE INDEX IF NOT EXISTS "IX_Productos_TipoProductoId" ON "Productos" ("tipo_producto_id");

CREATE TABLE IF NOT EXISTS "modelos_autobus" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "activo" BOOLEAN NOT NULL,
    "fabricante" TEXT NOT NULL,
    "nombre" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "lineas" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "activa" BOOLEAN NOT NULL,
    "color_primario" TEXT,
    "color_secundario" TEXT,
    "logo_url" TEXT,
    "nombre" TEXT NOT NULL,
    "nombre_operador" TEXT
);

CREATE TABLE IF NOT EXISTS "Pedidos" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "cantidad" INTEGER NOT NULL,
    "color" TEXT,
    "color_hex" TEXT,
    "estado" TEXT NOT NULL,
    "fecha_creacion" TIMESTAMP WITH TIME ZONE NOT NULL,
    "linea_id" INTEGER,
    "modelo_autobus_id" INTEGER,
    "nombre_operador" TEXT,
    "notas_especiales" TEXT,
    "numero_economico" TEXT,
    "producto_id" INTEGER NOT NULL,
    "ruta" TEXT,
    FOREIGN KEY ("linea_id") REFERENCES "lineas" ("id"),
    FOREIGN KEY ("modelo_autobus_id") REFERENCES "modelos_autobus" ("id"),
    FOREIGN KEY ("producto_id") REFERENCES "productos" ("id")
);

CREATE INDEX IF NOT EXISTS "IX_Pedidos_LineaId" ON "Pedidos" ("linea_id");
CREATE INDEX IF NOT EXISTS "IX_Pedidos_ModeloAutobusId" ON "Pedidos" ("modelo_autobus_id");
CREATE INDEX IF NOT EXISTS "IX_Pedidos_ProductoId" ON "Pedidos" ("producto_id");

-- =============================================
-- Insertar datos iniciales
-- =============================================

-- Insertar roles si no existen
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM "AspNetRoles" WHERE "Name" = 'Administrador') THEN
        INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
        VALUES ('1', '1', 'Administrador', 'ADMINISTRADOR');
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM "AspNetRoles" WHERE "Name" = 'Cliente') THEN
        INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
        VALUES ('2', '2', 'Cliente', 'CLIENTE');
    END IF;
END $$;

-- Insertar tipos de producto iniciales (ejemplos)
INSERT INTO "tipos_producto" ("max_caracteres", "nombre", "permite_nombre", "permite_numero_economico", "permite_ruta")
SELECT 50, 'Camiseta', true, true, false
WHERE NOT EXISTS (SELECT 1 FROM "tipos_producto" WHERE "nombre" = 'Camiseta');

INSERT INTO "tipos_producto" ("max_caracteres", "nombre", "permite_nombre", "permite_numero_economico", "permite_ruta")
SELECT 30, 'Gorra', true, false, false
WHERE NOT EXISTS (SELECT 1 FROM "tipos_producto" WHERE "nombre" = 'Gorra');

INSERT INTO "tipos_producto" ("max_caracteres", "nombre", "permite_nombre", "permite_numero_economico", "permite_ruta")
SELECT 100, 'Chaqueta', true, true, true
WHERE NOT EXISTS (SELECT 1 FROM "tipos_producto" WHERE "nombre" = 'Chaqueta');

INSERT INTO "tipos_producto" ("max_caracteres", "nombre", "permite_nombre", "permite_numero_economico", "permite_ruta")
SELECT 30, 'Peluche', true, false, false
WHERE NOT EXISTS (SELECT 1 FROM "tipos_producto" WHERE "nombre" = 'Peluche');

INSERT INTO "tipos_producto" ("max_caracteres", "nombre", "permite_nombre", "permite_numero_economico", "permite_ruta")
SELECT 20, 'Comfort Gear', true, false, false
WHERE NOT EXISTS (SELECT 1 FROM "tipos_producto" WHERE "nombre" = 'Comfort Gear');

INSERT INTO "tipos_producto" ("max_caracteres", "nombre", "permite_nombre", "permite_numero_economico", "permite_ruta")
SELECT 25, 'Accesorio', true, false, false
WHERE NOT EXISTS (SELECT 1 FROM "tipos_producto" WHERE "nombre" = 'Accesorio');

-- =============================================
-- Mensaje de finalización
-- =============================================

DO $$
BEGIN
    RAISE NOTICE 'Configuración de base de datos completada exitosamente.';
    RAISE NOTICE 'Base de datos: xa57_db';
    RAISE NOTICE 'Usuario por defecto para conexión: postgres';
    RAISE NOTICE 'Verifique su archivo appsettings.json para la cadena de conexión.';
END $$;