-- =============================================
-- Script de configuración de base de datos para XA57_Proyecto
-- Este script crea la base de datos completa con todas las tablas y datos iniciales
-- Compatible con PostgreSQL
-- Última actualización: 2026-04-16
-- =============================================

-- Crear base de datos si no existe
DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_database WHERE datname = 'xa57_db') THEN
        CREATE DATABASE xa57_db;
        RAISE NOTICE 'Base de datos xa57_db creada.';
    ELSE
        RAISE NOTICE 'La base de datos xa57_db ya existe.';
    END IF;
END $$;

-- Conectar a la base de datos xa57_db
\c xa57_db;

-- =============================================
-- Tablas de Identity de ASP.NET Core
-- =============================================

CREATE TABLE IF NOT EXISTS "AspNetRoles" (
    "Id" TEXT NOT NULL PRIMARY KEY,
    "ConcurrencyStamp" TEXT,
    "Name" CHARACTER VARYING(256),
    "NormalizedName" CHARACTER VARYING(256)
);

CREATE UNIQUE INDEX IF NOT EXISTS "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE TABLE IF NOT EXISTS "AspNetRoleClaims" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ClaimType" TEXT,
    "ClaimValue" TEXT,
    "RoleId" TEXT NOT NULL,
    FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE TABLE IF NOT EXISTS "AspNetUserClaims" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ClaimType" TEXT,
    "ClaimValue" TEXT,
    "UserId" TEXT NOT NULL,
    FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE TABLE IF NOT EXISTS "AspNetUserLogins" (
    "LoginProvider" CHARACTER VARYING(128) NOT NULL,
    "ProviderKey" CHARACTER VARYING(128) NOT NULL,
    "ProviderDisplayName" TEXT,
    "UserId" TEXT NOT NULL,
    PRIMARY KEY ("LoginProvider", "ProviderKey"),
    FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE TABLE IF NOT EXISTS "AspNetUserRoles" (
    "UserId" TEXT NOT NULL,
    "RoleId" TEXT NOT NULL,
    PRIMARY KEY ("UserId", "RoleId"),
    FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE TABLE IF NOT EXISTS "AspNetUserTokens" (
    "UserId" TEXT NOT NULL,
    "LoginProvider" CHARACTER VARYING(128) NOT NULL,
    "Name" CHARACTER VARYING(128) NOT NULL,
    "Value" TEXT,
    PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "AspNetUsers" (
    "Id" TEXT NOT NULL PRIMARY KEY,
    "AccessFailedCount" INTEGER NOT NULL,
    "Apellido" CHARACTER VARYING(100) NOT NULL,
    "ConcurrencyStamp" TEXT,
    "Email" CHARACTER VARYING(256),
    "EmailConfirmed" BOOLEAN NOT NULL,
    "LockoutEnabled" BOOLEAN NOT NULL,
    "LockoutEnd" TIMESTAMP WITH TIME ZONE,
    "Nombre" CHARACTER VARYING(100) NOT NULL,
    "NormalizedEmail" CHARACTER VARYING(256),
    "NormalizedUserName" CHARACTER VARYING(256),
    "PasswordHash" TEXT,
    "PhoneNumber" TEXT,
    "PhoneNumberConfirmed" BOOLEAN NOT NULL,
    "SecurityStamp" TEXT,
    "TwoFactorEnabled" BOOLEAN NOT NULL,
    "UserName" CHARACTER VARYING(256)
);

CREATE UNIQUE INDEX IF NOT EXISTS "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
CREATE INDEX IF NOT EXISTS "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

-- =============================================
-- Tablas del Dominio (Modelo de Dominio v1.1)
-- =============================================

-- Categorías (nueva)
CREATE TABLE IF NOT EXISTS "categorias" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "descripcion" TEXT,
    "nombre" TEXT NOT NULL
);

-- Tipos de Producto
CREATE TABLE IF NOT EXISTS "tipos_producto" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "max_caracteres" INTEGER NOT NULL DEFAULT 20,
    "nombre" TEXT NOT NULL,
    "permite_nombre" BOOLEAN NOT NULL DEFAULT TRUE,
    "permite_numero_economico" BOOLEAN NOT NULL DEFAULT TRUE,
    "permite_ruta" BOOLEAN NOT NULL DEFAULT TRUE
);

-- Productos (actualizado con nuevos campos)
CREATE TABLE IF NOT EXISTS "productos" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "activo" BOOLEAN NOT NULL DEFAULT TRUE,
    "categoria_id" INTEGER,
    "descripcion" TEXT,
    "es_personalizable" BOOLEAN NOT NULL DEFAULT FALSE,
    "imagen_url" TEXT,
    "nombre" TEXT NOT NULL,
    "precio" NUMERIC NOT NULL,
    "stock" INTEGER NOT NULL DEFAULT 0,
    "tipo_producto_id" INTEGER,
    FOREIGN KEY ("categoria_id") REFERENCES "categorias" ("id"),
    FOREIGN KEY ("tipo_producto_id") REFERENCES "tipos_producto" ("id")
);

CREATE INDEX IF NOT EXISTS "IX_productos_categoria_id" ON "productos" ("categoria_id");
CREATE INDEX IF NOT EXISTS "IX_productos_tipo_producto_id" ON "productos" ("tipo_producto_id");

-- Modelos de Autobús
CREATE TABLE IF NOT EXISTS "modelos_autobus" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "activo" BOOLEAN NOT NULL DEFAULT TRUE,
    "fabricante" TEXT,
    "nombre" TEXT NOT NULL
);

-- Líneas
CREATE TABLE IF NOT EXISTS "lineas" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "activa" BOOLEAN NOT NULL DEFAULT TRUE,
    "color_primario" TEXT,
    "color_secundario" TEXT,
    "logo_url" TEXT,
    "nombre" TEXT NOT NULL,
    "nombre_operador" TEXT
);

-- Pedidos (ítems del carrito - incluye campos de personalización)
CREATE TABLE IF NOT EXISTS "Pedidos" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "cantidad" INTEGER NOT NULL,
    "color" TEXT,
    "color_hex" TEXT,
    "estado" TEXT NOT NULL DEFAULT 'Recibido',
    "fecha_creacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "linea_id" INTEGER,
    "modelo_autobus_id" INTEGER,
    "nombre_operador" TEXT,
    "notas_especiales" TEXT,
    "numero_economico" TEXT,
    "producto_id" INTEGER NOT NULL,
    "ruta" TEXT,
    FOREIGN KEY ("linea_id") REFERENCES "lineas" ("id"),
    FOREIGN KEY ("modelo_autobus_id") REFERENCES "modelos_autobus" ("id"),
    FOREIGN KEY ("producto_id") REFERENCES "productos" ("id")
);

CREATE INDEX IF NOT EXISTS "IX_Pedidos_linea_id" ON "Pedidos" ("linea_id");
CREATE INDEX IF NOT EXISTS "IX_Pedidos_modelo_autobus_id" ON "Pedidos" ("modelo_autobus_id");
CREATE INDEX IF NOT EXISTS "IX_Pedidos_producto_id" ON "Pedidos" ("producto_id");

-- Personalizaciones de Producto (nueva)
CREATE TABLE IF NOT EXISTS "personalizaciones_producto" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "precio_extra" NUMERIC NOT NULL DEFAULT 0,
    "tipo_opcion" TEXT NOT NULL,
    "valor_opcion" TEXT NOT NULL
);

-- Carritos (nueva)
CREATE TABLE IF NOT EXISTS "carritos" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "fecha_creacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "usuario_id" INTEGER NOT NULL
);

-- Items de Carrito (nueva)
CREATE TABLE IF NOT EXISTS "items_carrito" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "cantidad" INTEGER NOT NULL,
    "carrito_id" INTEGER NOT NULL,
    "producto_id" INTEGER NOT NULL,
    FOREIGN KEY ("carrito_id") REFERENCES "carritos" ("id") ON DELETE CASCADE,
    FOREIGN KEY ("producto_id") REFERENCES "productos" ("id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_items_carrito_carrito_id" ON "items_carrito" ("carrito_id");
CREATE INDEX IF NOT EXISTS "IX_items_carrito_producto_id" ON "items_carrito" ("producto_id");

-- Órdenes (nueva)
CREATE TABLE IF NOT EXISTS "ordenes" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "estado" TEXT NOT NULL DEFAULT 'Recibido',
    "fecha_creacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "usuario_id" INTEGER NOT NULL
);

-- Items de Orden (nueva)
CREATE TABLE IF NOT EXISTS "items_orden" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "cantidad" INTEGER NOT NULL,
    "orden_id" INTEGER NOT NULL,
    "PersonalizacionId" INTEGER,
    "producto_id" INTEGER NOT NULL,
    FOREIGN KEY ("orden_id") REFERENCES "ordenes" ("id") ON DELETE CASCADE,
    FOREIGN KEY ("PersonalizacionId") REFERENCES "personalizaciones_producto" ("id"),
    FOREIGN KEY ("producto_id") REFERENCES "productos" ("id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_items_orden_orden_id" ON "items_orden" ("orden_id");
CREATE INDEX IF NOT EXISTS "IX_items_orden_PersonalizacionId" ON "items_orden" ("PersonalizacionId");
CREATE INDEX IF NOT EXISTS "IX_items_orden_producto_id" ON "items_orden" ("producto_id");

-- =============================================
-- Tabla de Migraciones de EF Core
-- =============================================

CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" CHARACTER VARYING(150) NOT NULL PRIMARY KEY,
    "ProductVersion" CHARACTER VARYING(32) NOT NULL
);

-- =============================================
-- Insertar datos iniciales
-- =============================================

-- Insertar roles si no existen
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM "AspNetRoles" WHERE "Name" = 'Administrador') THEN
        INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
        VALUES ('1', '1', 'Administrador', 'ADMINISTRADOR');
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM "AspNetRoles" WHERE "Name" = 'Cliente') THEN
        INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
        VALUES ('2', '2', 'Cliente', 'CLIENTE');
    END IF;
END $$;

-- Insertar categorías iniciales
INSERT INTO "categorias" ("nombre", "descripcion")
SELECT 'Souvenirs', 'Artículos de recuerdo y regalo'
WHERE NOT EXISTS (SELECT 1 FROM "categorias" WHERE "nombre" = 'Souvenirs');

INSERT INTO "categorias" ("nombre", "descripcion")
SELECT 'Accesorios', 'Accesorios varios'
WHERE NOT EXISTS (SELECT 1 FROM "categorias" WHERE "nombre" = 'Accesorios');

-- Insertar tipos de producto iniciales
INSERT INTO "tipos_producto" ("max_caracteres", "nombre", "permite_nombre", "permite_numero_economico", "permite_ruta")
SELECT 50, 'Busito de Peluche', TRUE, TRUE, FALSE
WHERE NOT EXISTS (SELECT 1 FROM "tipos_producto" WHERE "nombre" = 'Busito de Peluche');

INSERT INTO "tipos_producto" ("max_caracteres", "nombre", "permite_nombre", "permite_numero_economico", "permite_ruta")
SELECT 30, 'Llavero', TRUE, FALSE, FALSE
WHERE NOT EXISTS (SELECT 1 FROM "tipos_producto" WHERE "nombre" = 'Llavero');

INSERT INTO "tipos_producto" ("max_caracteres", "nombre", "permite_nombre", "permite_numero_economico", "permite_ruta")
SELECT 100, 'Almohada', TRUE, TRUE, TRUE
WHERE NOT EXISTS (SELECT 1 FROM "tipos_producto" WHERE "nombre" = 'Almohada');

INSERT INTO "tipos_producto" ("max_caracteres", "nombre", "permite_nombre", "permite_numero_economico", "permite_ruta")
SELECT 20, 'Camiseta', TRUE, FALSE, FALSE
WHERE NOT EXISTS (SELECT 1 FROM "tipos_producto" WHERE "nombre" = 'Camiseta');

INSERT INTO "tipos_producto" ("max_caracteres", "nombre", "permite_nombre", "permite_numero_economico", "permite_ruta")
SELECT 30, 'Gorra', TRUE, FALSE, FALSE
WHERE NOT EXISTS (SELECT 1 FROM "tipos_producto" WHERE "nombre" = 'Gorra');

-- Insertar modelos de autobús
INSERT INTO "modelos_autobus" ("activo", "fabricante", "nombre")
SELECT TRUE, 'Irizar', 'Irizar i8'
WHERE NOT EXISTS (SELECT 1 FROM "modelos_autobus" WHERE "nombre" = 'Irizar i8');

INSERT INTO "modelos_autobus" ("activo", "fabricante", "nombre")
SELECT TRUE, 'Volvo', 'Volvo 9800'
WHERE NOT EXISTS (SELECT 1 FROM "modelos_autobus" WHERE "nombre" = 'Volvo 9800');

INSERT INTO "modelos_autobus" ("activo", "fabricante", "nombre")
SELECT TRUE, 'Mercedes-Benz', 'Mercedes-Benz Tourismo'
WHERE NOT EXISTS (SELECT 1 FROM "modelos_autobus" WHERE "nombre" = 'Mercedes-Benz Tourismo');

-- Insertar líneas de transporte
INSERT INTO "lineas" ("activa", "color_primario", "color_secundario", "logo_url", "nombre", "nombre_operador")
SELECT TRUE, '#FF0000', '#FFFFFF', NULL, 'ETN', 'Transportes ETN'
WHERE NOT EXISTS (SELECT 1 FROM "lineas" WHERE "nombre" = 'ETN');

INSERT INTO "lineas" ("activa", "color_primario", "color_secundario", "logo_url", "nombre", "nombre_operador")
SELECT TRUE, '#0000FF', '#FFFF00', NULL, 'Estrella Roja', 'Estrella Roja de los Fernández'
WHERE NOT EXISTS (SELECT 1 FROM "lineas" WHERE "nombre" = 'Estrella Roja');

INSERT INTO "lineas" ("activa", "color_primario", "color_secundario", "logo_url", "nombre", "nombre_operador")
SELECT TRUE, '#00AA00', '#FFFFFF', NULL, 'Primera Plus', 'Grupo Primera'
WHERE NOT EXISTS (SELECT 1 FROM "lineas" WHERE "nombre" = 'Primera Plus');

-- =============================================
-- Mensaje de finalización
-- =============================================

DO $$
BEGIN
    RAISE NOTICE '========================================';
    RAISE NOTICE 'Configuración de base de datos completada.';
    RAISE NOTICE 'Base de datos: xa57_db';
    RAISE NOTICE 'Tablas creadas/verificadas:';
    RAISE NOTICE '  - Identity: AspNetUsers, AspNetRoles, etc.';
    RAISE NOTICE '  - Dominio: categorias, productos, modelos_autobus,';
    RAISE NOTICE '              lineas, Pedidos, carritos, ordenes, etc.';
    RAISE NOTICE '========================================';
END $$;
